### ISSUE TITLE
LZB Failed in cabin change

### ISSUE THREAD

**Issue by serrgiofdezz** [cesarBLG/ETCS#8]
Hola @cesarBLG, tengo el siguiente problema con el programa ETCS con el sistema LZB al cambiar de cabina para cambiar de dirección

## Test
1. Iniciar ASFA, luego ETCS
2. Introducir datos en el DMI y usar LZB
3. Cambiar de cabina

Al cambiar de cabina, aparece en el DMI que LZB no está disponible:
![lzb](https://user-images.githubusercontent.com/45104843/232235021-7b974d31-48b0-4d83-a99a-47e93fb68f2c.PNG)

He probado lo siguiente
* A cambiar de modos (Level 0, luego LZB)
* A reiniciar el sistema ETCS: pero al poner de nuevo los datos y seleccionar el sistema LZB, sigue apareciendo el problema

Destacar que ningún otro modo funciona tras el cambio de cabina (aunque no aparezca error). El nivel 0 (con uso del ASFA) parece funcionar pero al detectar movimiento, aplica el freno de emergencia. Lo mismo con el nivel 1.

También destacar que si se realiza de nuevo el cambio de cabina a la original, el sistema tanto LZB como los demás empiezan a funcionar perfectamente.

¿Cuál es el problema? ¿Hay algún procedimiento a realizar para el cambio de cabina?

Si puedo aportar tests o logs, estoy dispuesto a ello.
Gracias!

P.D.: Las pruban se han hecho con la versión 0.3 ya que veo que habeis realizado cambios recientes)

**Comment by cesarBLG** [comment]
Hola:
No estoy seguro de si la versión del script que publiqué ya estaba arreglada, pero anteriormente por tema de odometría no se podía conducir desde cabinas traseras. Aquí está la última actualización: https://we.tl/t-E8UwkTwbWd

Por otra parte, lo del LZB está más bien relacionado con el procedimiento de cambio de cabina. Es necesario que esté definida la "Master Key", de forma que al habilitar cabina conectando la Master Key arranque correctamente el STM. Es decir, al cambiar de cabina se debe deshabilitar una cabina y habilitar la contraria

**Comment by serrgiofdezz** [comment]
> Hola: No estoy seguro de si la versión del script que publiqué ya estaba arreglada, pero anteriormente por tema de odometría no se podía conducir desde cabinas traseras. Aquí está la última actualización: https://we.tl/t-E8UwkTwbWd
> 
> Por otra parte, lo del LZB está más bien relacionado con el procedimiento de cambio de cabina. Es necesario que esté definida la "Master Key", de forma que al habilitar cabina conectando la Master Key arranque correctamente el STM. Es decir, al cambiar de cabina se debe deshabilitar una cabina y habilitar la contraria

Gracias! ¿Y cuál sería el procedimiento para deshabilitar la cabina para habilitar la otra?

**Comment by cesarBLG** [comment]
Básicamente hay que poner Master Key en el .eng correspondiente, y luego deshabilitas y habilitas con la master key.

**Comment by serrgiofdezz** [comment]
Sobre el archivo que has enviado... no estoy muy seguro donde hay que ponerlos. ¿Qué archivos hay que reemplazar?
Son archivos diferentes a los que vienen en la versión oficial 0.3

**Comment by cesarBLG** [comment]
- Archivo ETCS_win32: descomprimir en una carpeta cualquiera, contiene el ETCS
- Archivo ServerTCS.cs: mover a TRAINS/TRAINSET/Common_TCS_Spain/Script
- El resto de archivos son del ASFA, reemplazando a los anteriores.

**Comment by serrgiofdezz** [comment]
> * Archivo ETCS_win32:

Por alguna razón no tengo ese archivo para Windows, creo que has incluido el APK para Android.

**Comment by cesarBLG** [comment]
Cierto, aquí está: https://we.tl/t-tx6gurHfQe

**Comment by serrgiofdezz** [comment]
Buenos días, he probado la nueva versión y parece ya funcionar correctamente. Gracias!
